import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ServicesCard from '../components/ServicesCard'
import { Typography } from '@mui/material'


export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Test next app</title>
        <meta name="description" content="Generated by create next app" />

      </Head>

      <main >
        <Typography variant="h1">NextJS App Heading </Typography>
      </main>
      <ServicesCard />

    </div>
  )
}
